// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _02_WineProject.Data.Context;

#nullable disable

namespace _02_WineProject.Data.Migrations
{
    [DbContext(typeof(WineDbContext))]
    [Migration("20240828033435_ProdutoMigration")]
    partial class ProdutoMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_03_WineProject.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Marca")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("QtdeEstoque")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasDiscriminator().HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_03_WineProject.Domain.Entities.Produtos.Vinho", b =>
                {
                    b.HasBaseType("_03_WineProject.Domain.Entities.Produto");

                    b.Property<int>("TipoVinho")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Vinho");
                });
#pragma warning restore 612, 618
        }
    }
}
